name: CD - Continuous Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deploy no Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"